version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    working_dir: /var/www/html
    # Extends wp-theme map file
    extends:
      file: wp-theme.yml
      service: themes
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./service-worker.js:/var/www/html/service-worker.js
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
volumes:
  db:
